name: Build and Deploy Code

on: ['push', 'pull_request']

jobs: 
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: dynasty713?
      DATABASE_NAME: fastapi_dbm
      DATABASE_USERNAME: postgres
      SECRET_KEY: h3hrih304ih0rih03rihi0hwu9u428y734y29hr8y42yrh0580u8y308y72y08y24r
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.9
        uses: actions/setup-python@v2   
        with:
          python-version: "3.9"
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r requirements.txt
      - name: Testing with Pytest
        run: |
          pip install pytest
          pytest